# Generated by Django 4.0.3 on 2022-09-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_tag_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_pdf',
            name='file_name',
            field=models.CharField(default='default', max_length=200),
        ),
    ]
